name: Check CLA

on:
  issue_comment:
    types:
      - created
  pull_request_target:

jobs:
  check:
    if: >-
      !github.event.repository.fork
      && (
        github.event.issue.pull_request
        && github.event.comment.body == '@kenodegard-bot check'
        || github.event_name == 'pull_request_target'
      )
    runs-on: ubuntu-latest
    steps:
      - name: Check CLA
        uses: conda/actions/check-cla@check-cla
        with:
          repository: conda-sandbox/cla
          magic-command: '@kenodegard-bot check'
          author: Bot <105068560+kenodegard-bot@users.noreply.github.com>
          token: ${{ secrets.CLA_TOKEN }}
          pr-token: ${{ secrets.CLA_PR_TOKEN }}
          fork-token: ${{ secrets.CLA_FORK_TOKEN }}
