name: CLA

on:
  issue_comment:
    types:
      - created
  pull_request_target:

jobs:
  check:
    if: >-
      !github.event.repository.fork
      && (
        github.event.issue.pull_request
        && github.event.comment.body == '@conda-bot check'
        || github.event_name == 'pull_request'
      )
    runs-on: ubuntu-latest
    steps:
      - name: Check CLA
        uses: conda/actions/check-cla@check-cla
        with:
          repository: conda-sandbox/cla
          token: ${{ secrets.CLA_ACTION_TOKEN }}
          fork-token: ${{ secrets.CLA_FORK_TOKEN }}
